[package]
name = "actix-web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.209", features = ["derive"] }
sqlx = { version = "*", features = ["mysql", "runtime-tokio-native-tls"]}